package view;

import business.CandidateObserver;
import business.Client;
import business.PersonObverser;
import business.PuestoObserver;
import domain.Candidato;
import domain.Persona;
import domain.Puesto;
import java.util.ArrayList;
import java.util.List;
import java.util.Observable;
import java.util.Observer;
import javax.swing.JOptionPane;
import util.IConstants;

/**
 *
 * @author Nelson
 */
public class LoginView extends javax.swing.JPanel implements IConstants, Observer {

    private PrincipalWindow principalWindow;
    private List<CandidateView> candidateViews;
    private List<Candidato> candidates;

    /**
     * Creates new form LoginView
     *
     * @param principalWindow
     */
    public LoginView(PrincipalWindow principalWindow) {
        initComponents();
        this.principalWindow = principalWindow;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnCheckIdentity = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtIdentity = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        btnCheckIdentity.setText("Ingresar");
        btnCheckIdentity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCheckIdentityActionPerformed(evt);
            }
        });

        jLabel1.setText("Cliente De Votación STV");

        txtIdentity.setText("N° de Identificación");
        txtIdentity.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtIdentityFocusLost(evt);
            }
        });
        txtIdentity.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtIdentityMouseClicked(evt);
            }
        });

        jLabel3.setText("Ingrese su número de identificación");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(148, 148, 148)
                                .addComponent(btnCheckIdentity, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(134, 134, 134)
                                .addComponent(txtIdentity, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 282, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(134, 134, 134)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(105, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(txtIdentity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnCheckIdentity)
                .addGap(70, 70, 70))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCheckIdentityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCheckIdentityActionPerformed
        /*
        List<CandidateView> candidateViews = new ArrayList<>();
        for (int i = 0; i < 4; i++) {
          //  for (int j = 0; j < candidateViews[0].length; j++) {
                candidateViews.add(new CandidateView());
           // }
        }        
        PapeletaView papeletaView = new PapeletaView(candidateViews);
        frame.addPanel(papeletaView);
         */
        if (txtIdentity.getText().equals("N° de Identificación")) {
            JOptionPane.showMessageDialog(null, "Ingrese su identificación");
            return;
        }
        Client client = new Client(VALIDATE_IDENTIFITATION, txtIdentity.getText(), this);
        client.start();
    }//GEN-LAST:event_btnCheckIdentityActionPerformed

    private void txtIdentityMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtIdentityMouseClicked
        if (txtIdentity.getText().equals("N° de Identificación")) {
            txtIdentity.setText("");
        }
    }//GEN-LAST:event_txtIdentityMouseClicked

    private void txtIdentityFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtIdentityFocusLost
        if (txtIdentity.getText().isEmpty()) {
            txtIdentity.setText("N° de Identificación");
        }
    }//GEN-LAST:event_txtIdentityFocusLost


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCheckIdentity;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField txtIdentity;
    // End of variables declaration//GEN-END:variables

    @Override
    public void update(Observable o, Object arg) {
        if (o instanceof PersonObverser) {
            if (arg instanceof Integer) {
                int respond = (int) arg;
                switch (respond) {
                    case 1:                        
                        Client client = new Client(GET_CANDIDATES, this);
                        client.start();
                                                
                        break;
                    case 0:
                        JOptionPane.showMessageDialog(null, "No puede realizar la votación");
                        break;
                    case -1:
                        JOptionPane.showMessageDialog(null, "No existe un periodo de votación activo");
                        break;
                    default:
                        break;
                }
            } else if (arg instanceof Persona){
                Persona persona = (Persona) arg;
                principalWindow.setPersona(persona);
            }
        }
        if (o instanceof CandidateObserver){
            if (arg instanceof List){
                candidates = (List) arg;
                candidateViews = new ArrayList<>();
                for (Candidato candidate : candidates) {                    
                    CandidateView candidateView = new CandidateView();
                    candidateView.setLblName(candidate.getNombre());
                    candidateView.setLblOrganization(candidate.getAgrupacion());
                    candidateView.setPanelColor(candidate.getColor());
                    //candidateView.setLblImage(candidate.getFoto());
                    candidateViews.add(candidateView);
                }
                
                Client client = new Client(GET_POSITION, this);
                client.start();                                                
            }
        }
        if (o instanceof PuestoObserver){
            if (arg instanceof Puesto){                                
                Puesto puesto = (Puesto) arg;
                PapeletaView papeletaView = new PapeletaView(this, principalWindow, candidateViews);
                papeletaView.setPueto(puesto);
                papeletaView.setCandidatos(candidates);
                principalWindow.addPanel(papeletaView);
            }
        }
    }
}
