package view;

import java.util.ArrayList;
import java.util.List;
import javax.swing.JPanel;
import javax.swing.JScrollPane;

/**
 *
 * @author Nelson
 */
public class PapeletaView extends javax.swing.JPanel {

    private List<CandidateView> candidateView;
    private List<CandidateView> candidateSelected;

    private JScrollPane jScrollPane1;
    private JScrollPane jScrollPane2;
    private JPanel panel1;
    private JPanel panel2;
    
    private int cantidadCandidatos;

    /**
     * Creates new form PapeletaView
     *
     * @param candidateViews
     */
    public PapeletaView(List<CandidateView> candidateViews) {
        initComponents();
        this.candidateView = candidateViews;
        this.candidateSelected = new ArrayList<>();
        this.cantidadCandidatos = candidateView.size();
        
        panel1 = new JPanel();        
        jScrollPane1 = new JScrollPane(panel1);        
        jScrollPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JScrollPane1MouseClicked(evt);
            }
        });
        add(jScrollPane1).setBounds(10, 10, 467, 345);
        panel2 = new JPanel();        
        jScrollPane2 = new JScrollPane(panel2);
        jScrollPane2.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JScrollPane2MouseClicked(evt);
            }
        });
        add(jScrollPane2).setBounds(650, 10, 467, 345);
        init();
    }

    private void init() {
        for (int i = 0; i < candidateView.size(); i++) {
            panel1.add(candidateView.get(i)).setBounds(i * 145, 0, 145, 315);
            PapeletaEmptyView emptyView = new PapeletaEmptyView();
            emptyView.setLabelNumber((i + 1) + "");
            panel2.add(emptyView).setBounds(i*140, 0, 145, 315);
            panel2.revalidate();
            jScrollPane1.revalidate();
            jScrollPane1.repaint();                        
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1152, 663));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1152, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 663, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void JScrollPane1MouseClicked (java.awt.event.MouseEvent evt){
        int i = evt.getX() / 145;
        if (candidateView.size() > 0){
            try {
                CandidateView candidato = candidateView.get(i);
                candidateView.remove(candidato);
                candidateSelected.add(candidato);
                renderCandidates();
            } catch (ClassCastException | IndexOutOfBoundsException e){
                
            }            
        }
    }
    
    private void JScrollPane2MouseClicked (java.awt.event.MouseEvent evt){
        int i = evt.getX() / 145;
        if (candidateSelected.size() > 0){
            try {
                CandidateView candidato = candidateSelected.get(i);
                candidateSelected.remove(candidato);
                candidateView.add(candidato);
                renderCandidates();
            } catch (ClassCastException | IndexOutOfBoundsException e){
                
            }            
        }
    }

    private void renderCandidates() {
        panel1.removeAll();
        panel2.removeAll();
        for (int i = 0; i < cantidadCandidatos; i++) {
            try {            
                panel1.add(candidateView.get(i)).setBounds(i * 145, 0, 145, 315);
            } catch (IndexOutOfBoundsException e){
                PapeletaEmptyView papeletaEmptyView = new PapeletaEmptyView();
                papeletaEmptyView.setLabelNumber("-");
                panel1.add(papeletaEmptyView).setBounds(i *145, 0, 145, 315);
            }            
        }    
        
        for (int i = 0; i < cantidadCandidatos; i++) {
            try {            
                panel2.add(candidateSelected.get(i)).setBounds(i * 145, 0, 145, 315);
            } catch (IndexOutOfBoundsException e) {
                PapeletaEmptyView papeletaEmptyView = new PapeletaEmptyView();
                papeletaEmptyView.setLabelNumber(i + "");
                panel2.add(papeletaEmptyView).setBounds(i *145, 0, 145, 315);
            }
        }
        panel1.revalidate();
        panel2.revalidate();
        panel1.repaint();
        panel2.repaint();
        jScrollPane1.revalidate();
        jScrollPane1.repaint();
        jScrollPane2.revalidate();
        jScrollPane2.repaint();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
