package view;

import domain.Puesto;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;

/**
 *
 * @author Nelson
 */
public class PapeletaView extends javax.swing.JPanel {

    private List<CandidateView> candidateView;
    private List<CandidateView> candidateSelected;

    private JScrollPane jScrollPane1;
    private JScrollPane jScrollPane2;
    private JPanel panel1;
    private JPanel panel2;
    
    private int cantidadCandidatos;

    /**
     * Creates new form PapeletaView
     *
     * @param candidateViews
     */
    public PapeletaView(List<CandidateView> candidateViews) {
        initComponents();
        this.candidateView = candidateViews;
        this.candidateSelected = new ArrayList<>();
        this.cantidadCandidatos = candidateView.size();
        
        panel1 = new JPanel();        
        jScrollPane1 = new JScrollPane(panel1);        
        jScrollPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JScrollPane1MouseClicked(evt);
            }
        });
        add(jScrollPane1).setBounds(10, 100, 467, 345);
        panel2 = new JPanel();        
        jScrollPane2 = new JScrollPane(panel2);
        jScrollPane2.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                JScrollPane2MouseClicked(evt);
            }
        });
        add(jScrollPane2).setBounds(650, 100, 467, 345);
        init();
    }

    private void init() {
        for (int i = 0; i < candidateView.size(); i++) {
            panel1.add(candidateView.get(i)).setBounds(i * 145, 0, 145, 315);
            PapeletaEmptyView emptyView = new PapeletaEmptyView();
            emptyView.setLabelNumber((i + 1) + "");
            panel2.add(emptyView).setBounds(i*140, 0, 145, 315);
            panel2.revalidate();
            jScrollPane1.revalidate();
            jScrollPane1.repaint();                        
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelPuesto = new javax.swing.JLabel();
        labelOrganizacion = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1152, 663));

        labelPuesto.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        labelPuesto.setText("jLabel1");

        labelOrganizacion.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        labelOrganizacion.setText("jLabel1");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Elección de:");

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton1.setText("Finalizar votación");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(514, 514, 514)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelOrganizacion, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelPuesto, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(523, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(127, 127, 127)
                .addComponent(jLabel1)
                .addGap(27, 27, 27)
                .addComponent(labelPuesto)
                .addGap(18, 18, 18)
                .addComponent(labelOrganizacion, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 361, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (candidateSelected.size() == 0){
            int confirmacion = JOptionPane.showConfirmDialog(null, "No ha asignado nigún voto, ¿Continuar?");
            if (confirmacion == 1 || confirmacion == 2)
                return;
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void JScrollPane1MouseClicked (java.awt.event.MouseEvent evt){
        int i = evt.getX() / 145;
        if (candidateView.size() > 0){
            try {
                CandidateView candidato = candidateView.get(i);
                candidateView.remove(candidato);
                candidateSelected.add(candidato);
                renderCandidates();
            } catch (ClassCastException | IndexOutOfBoundsException e){
                
            }            
        }
    }
    
    private void JScrollPane2MouseClicked (java.awt.event.MouseEvent evt){
        int i = evt.getX() / 145;
        if (candidateSelected.size() > 0){
            try {
                CandidateView candidato = candidateSelected.get(i);
                candidateSelected.remove(candidato);
                candidateView.add(candidato);
                renderCandidates();
            } catch (ClassCastException | IndexOutOfBoundsException e){
                
            }            
        }
    }

    private void renderCandidates() {
        panel1.removeAll();
        panel2.removeAll();
        for (int i = 0; i < cantidadCandidatos; i++) {
            try {            
                panel1.add(candidateView.get(i)).setBounds(i * 145, 0, 145, 315);
            } catch (IndexOutOfBoundsException e){
                PapeletaEmptyView papeletaEmptyView = new PapeletaEmptyView();
                papeletaEmptyView.setLabelNumber("-");
                panel1.add(papeletaEmptyView).setBounds(i *145, 0, 145, 315);
            }            
        }    
        
        for (int i = 0; i < cantidadCandidatos; i++) {
            try {            
                panel2.add(candidateSelected.get(i)).setBounds(i * 145, 0, 145, 315);
            } catch (IndexOutOfBoundsException e) {
                PapeletaEmptyView papeletaEmptyView = new PapeletaEmptyView();
                papeletaEmptyView.setLabelNumber((i + 1) + "");
                panel2.add(papeletaEmptyView).setBounds(i * 145, 0, 145, 315);
            }
        }
        panel1.revalidate();
        panel2.revalidate();
        panel1.repaint();
        panel2.repaint();
        jScrollPane1.revalidate();
        jScrollPane1.repaint();
        jScrollPane2.revalidate();
        jScrollPane2.repaint();
    }

    public void setPueto(Puesto puesto){
        labelPuesto.setText(puesto.getNombre());
        labelOrganizacion.setText(puesto.getOrganizacion());
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel labelOrganizacion;
    private javax.swing.JLabel labelPuesto;
    // End of variables declaration//GEN-END:variables
}
